CREATE TABLE `app_payment_wechat_config` (
                                             `id` bigint(20) NOT NULL,
                                             `app_id` bigint(20) DEFAULT NULL COMMENT 'app的id',
                                             `pkg` varchar(255) DEFAULT NULL COMMENT 'pkg',
                                             `we_chat_app_id` varchar(63) DEFAULT NULL COMMENT '微信appId',
                                             `we_chat_mchid` varchar(32) DEFAULT NULL COMMENT '微信支付商户号',
                                             `we_chat_app_secret` varchar(63) DEFAULT NULL COMMENT '微信开放平台密钥',
                                             `we_chat_api_key` varchar(63) DEFAULT NULL COMMENT '微信支付api密钥key',
                                             `we_chat_api_cert` text COMMENT '微信支付api证书（base64编码后）',
                                             `we_chat_mch_private_key` text COMMENT '微信支付平台商户私钥',
                                             `we_chat_mch_cert_serial_no` varchar(127) DEFAULT NULL COMMENT '微信平台商户证书序列号',
                                             `we_chat_api_v3_key` varchar(127) DEFAULT NULL COMMENT '微信API v3 Key',
                                             `frozen_status` int(3) DEFAULT NULL COMMENT '冻结状态；0:未冻结，1:冻结',
                                             `merchant_name` varchar(255) DEFAULT NULL COMMENT '主体名称，商户名称',
                                             `deleted` int(11) DEFAULT NULL COMMENT '逻辑删除字段；0:已删除，1:未删除',
                                             `create_time` datetime DEFAULT NULL COMMENT '创建时间',
                                             `create_by` varchar(127) DEFAULT NULL COMMENT '创建者',
                                             `last_modify_time` datetime DEFAULT NULL COMMENT '最近修改时间',
                                             `last_modify_by` varchar(127) DEFAULT NULL COMMENT '最近修改者',
                                             PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='应用支付的微信支付信息配置';