CREATE TABLE `finite_task_log` (
  `id` bigint(20) NOT NULL,
  `user_id` bigint(20) NOT NULL,
  `task_code` varchar(31) NOT NULL,
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP,
  `round` int(11) DEFAULT NULL,
  `begin_time` bigint(20) DEFAULT NULL,
  `duration` bigint(20) DEFAULT NULL,
  `object_id` varchar(1023) DEFAULT NULL,
  `number` bigint(20) DEFAULT NULL,
  `goldBean` bigint(20) DEFAULT NULL,
  `amount` bigint(20) DEFAULT NULL,
  `score` bigint(20) DEFAULT NULL,
  `task_type` int(11) DEFAULT NULL,
  `app_id` bigint(20) NOT NULL,
  `active_days` int(11) DEFAULT '-1',
  `link_id` bigint(20) DEFAULT NULL COMMENT '关联的task_log_id',
  `spin_mult` double(5,2) DEFAULT '0.00',
  `invit_rewards` varchar(255) DEFAULT NULL COMMENT '开始任务时的奖励配置列表',
  `amount_exch_ratio` bigint(20) DEFAULT NULL COMMENT '开始任务时的金币与现金的兑换率',
  `invited_user_id` bigint(20) DEFAULT NULL COMMENT '被邀请人的id',
  `modify_time` datetime DEFAULT CURRENT_TIMESTAMP,
  `doubled` bit(1) DEFAULT NULL COMMENT '是否已经双倍了',
  `app_version` varchar(63) DEFAULT NULL COMMENT '完成任务时的版本',
  `invit_reward_gived_count` int(63) DEFAULT '0' COMMENT '邀请好友任务已经给予奖励的次数',
  `invit_task_completed` bit(1) DEFAULT b'0' COMMENT '邀请好友任务奖励是否全都发放完成了',
  `medal_type` int(11) DEFAULT NULL COMMENT '勋章任务类型',
  `medal_condition_value` int(11) DEFAULT NULL COMMENT '勋章任务奖励条件值',
  `token` varchar(63) DEFAULT NULL COMMENT '请求时携带的token',
  PRIMARY KEY (`id`),
  KEY `USER_ID_TASK_CODE_INDEX` (`user_id`,`task_code`),
  KEY `USER_ID_TASK_CODE_ROUND_DURATION` (`user_id`,`task_code`,`round`,`duration`),
  KEY `USER_ID_TASK_CODE_CREATE_TIME` (`user_id`,`task_code`,`create_time`),
  KEY `USER_ID_TASK_CODE_ACTIVE_DAYS_INDEX` (`user_id`,`task_code`,`active_days`),
  KEY `USER_ID_TASK_CODE_CREATE_TIME_NUMBER` (`user_id`,`task_code`,`create_time`,`number`),
  KEY `USER_ID_INVIT_UID_CREATE_TIME_INDEX` (`user_id`,`invited_user_id`,`create_time`),
  KEY `USER_ID_INVIT_UID_TCODE_MTIME_INVTRWGVCNT_INDEX` (`user_id`,`invited_user_id`,`task_code`,`modify_time`,`invit_reward_gived_count`),
  KEY `USER_ID_INVTTKCOMP_CREATE_TIME_NUMBER` (`user_id`,`invit_task_completed`,`create_time`,`number`),
  KEY `UID_TCODE_MTYPE_MCDTVALUE_CTIME_INDEX` (`user_id`,`task_code`,`medal_type`,`medal_condition_value`,`create_time`),
  KEY `UID_TCODE_ACDAYS_CTIME_INDEX` (`user_id`,`task_code`,`active_days`,`create_time`),
  KEY `USER_ID_CREATE_TIME_INDEx` (`user_id`,`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;