CREATE TABLE `refund_order` (
    `id` bigint COMMENT '主键',
    `pay_order_id` bigint not null COMMENT '管理的支付订单id',
    `channel` int not null DEFAULT 0 COMMENT '支付渠道, 0:微信, 1:待定',
    `third_transaction_id` varchar(255) COMMENT '第三方支付订单号',
    `third_mchid` varchar(255) not null COMMENT '第三方商户id',
    `third_app_id` varchar(255) not null COMMENT '第三方appid',
    `third_out_trade_no` varchar(255) COMMENT '第三方支付订单id，由我们内部生成',
    `third_out_refund_no` varchar(255) COMMENT '第三方退款订单id，由我们内部生成',
    `third_pay_type` int not null COMMENT '第三方支付类型, 0:JSAPI支付, 1:APP支付',
    `third_user_received_account` varchar(255) COMMENT '第三方退款入账账户',
    `app_id` bigint not null COMMENT '我们平台的appid',
    `user_id` bigint not null COMMENT '我们平台的用户id',
    `type` int not null COMMENT '支付类型，业务字段，不同的app自己定义自己的支付类型，如果不需要区分类型可以不填',
    `amount` bigint not null COMMENT '支付金额(单位：分)',
    `status` int not null DEFAULT 0 COMMENT '订单状态，0-未支付，1-支付成功，2-支付失败',
    `third_error_code` varchar(255) COMMENT '第三方支付错误码',
    `third_error_msg` varchar(255) COMMENT '第三方支付错误信息',
    `completion_time` datetime COMMENT '退款订单完成时间',
    `create_time` datetime not null DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `modify_time` datetime not null DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`),
    KEY `THIRD_OUT_TRADE_NO_INDEX` (`third_out_trade_no`),
    KEY `THIRD_OUT_REFUND_NO_INDEX` (`third_out_refund_no`),
    KEY `PAY_ORDER_ID` (`pay_order_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT '退款订单表';