name: Prettier

on:
  push:
    branches:
    - main

jobs:
  prettier:
    runs-on: ubuntu-latest
    if: github.repository == 'doocs/jvm'
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}

    - name: Prettify code
      uses: creyD/prettier_action@v3.2
      with:
        prettier_options: --write **/*.{html,js,md}
        commit_message: 'style: prettify code and document'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
